// This file will be auto-generated by Supabase CLI
// For now, we define a basic type structure
// TODO: Generate types using: supabase gen types typescript --project-id <project-id> > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      dashboard_tasks: {
        Row: {
          id: string;
          created_at: string;
          user_id: string;
          title: string;
          completed: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          user_id: string;
          title: string;
          completed?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          user_id?: string;
          title?: string;
          completed?: boolean;
        };
      };
    };
    Views: {
      [key: string]: {
        Row: Record<string, unknown>;
      };
    };
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: {
      [key: string]: string;
    };
  };
}

